Author Name Recipe
coralproject/talk-recipes pull request #2
Opened 2017-08-21 15:26 UTC by okbel

## What does this PR do?
- New Recipe: Author Name Recipe: **Member Since**
  https://www.pivotaltracker.com/story/show/150178457

### Author Name Recipe: **Member Since** - Preview
<img width="315" alt="screen shot 2017-08-21 at 12 15 26 pm" src="https://user-images.githubusercontent.com/1401559/29526181-5700aa64-866b-11e7-95f5-967230eba9d2.png">

2017-08-21 16:37 UTC, cvle commented on plugins/author-name/client/components/Tooltip.js
> +      {console.log(memberSinceDate)}
Was this forgotten?

2017-08-21 16:38 UTC, cvle commented on plugins/author-name/package.json
> +  "version": "1.0.0",
I prefer starting with `0.x.x` as the initial version number :-D

2017-08-21 16:42 UTC, cvle commented on plugins/author-name/client/containers/AuthorName.js
> +      {...this}
Avoid `{...this}` this just passes everything, even the `render` function. It's better to be explicit, so what is passed down is clearly defined: 

```js
<AuthorName 
comment={this.props.comment}
showTooltip={this.showTooltip}
hideTooltip={this.hideTooltip}
tooltipVisible={this.state.tooltip}
/>
```

2017-08-21 16:44 UTC, cvle commented on plugins/author-name/client/components/AuthorName.js
> +export default ({props: {comment}, state: {tooltip}, showTooltip, hideTooltip}) => {
See below

2017-08-21 16:45 UTC, alinhle requested changes
See comments

2017-08-22 15:26 UTC, okbel commented on plugins/author-name/client/components/Tooltip.js
> +      {console.log(memberSinceDate)}
Of course 😬

2017-08-22 15:26 UTC, okbel commented on plugins/author-name/package.json
> +  "version": "1.0.0",
👍  I like it too

2017-08-22 15:26 UTC, okbel commented on plugins/author-name/client/containers/AuthorName.js
> +      {...this}
Agreed.

2017-08-23 09:34 UTC, cvle commented on plugins/author-name/client/containers/AuthorName.js
> +      tooltip={this.state.tooltip}
This should be `tooltipVisible={...`

2017-08-23 09:38 UTC, cvle commented on plugins/author-name/client/components/Tooltip.js
> +      {t('talk-plugin-author-name.member_since')}: {moment(memberSinceDate).format('MMMM DD, YYYY')}
![image](https://user-images.githubusercontent.com/14221600/29609330-2317b2f0-87f7-11e7-85b7-26d4cf9d80ca.png)
According to `moment` documentation you must provide a format string as a second value: `moment(memberSinceData, dateFormat).format('MMMM DD, YYYY');`

2017-08-23 15:44 UTC, alinhle approved these changes

2017-08-23 16:29 UTC, cvle commented
I think we should add an entry in the README file. @okbel

2017-08-23 17:20 UTC, merged